language: rust

matrix:
  include:
    - env: TARGET_BUILD=thumbv6m-none-eabi
      rust: nightly-2018-04-19
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - binutils-arm-none-eabi

    - env: TARGET_BUILD=thumbv7m-none-eabi
      rust: nightly-2018-04-19
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - binutils-arm-none-eabi

    - env: TARGET_BUILD=thumbv7em-none-eabi
      rust: nightly-2018-04-19
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - binutils-arm-none-eabi

    - env: TARGET_BUILD=thumbv7em-none-eabihf
      rust: nightly-2018-04-19
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - binutils-arm-none-eabi

before_install: set -e

install:
  - rustup target add $TARGET_BUILD

script:
  - cargo build --target $TARGET_BUILD
  - cargo build --target $TARGET_BUILD --release

after_script: set +e

cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
