language: rust

matrix:
  include:
    - env: TARGET=thumbv6m-none-eabi
    - env: TARGET=thumbv7em-none-eabi
    - env: TARGET=thumbv7em-none-eabihf
    - env: TARGET=thumbv7m-none-eabi

before_install: 
  - set -e
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly
  - rustup self update
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-none-eabi 

install:
  - rustup override set nightly
  - rustup component add rust-src
  - rustup target add arm-unknown-linux-gnueabi
  - rustup target add armv7-unknown-linux-gnueabihf
  - source ~/.cargo/env || true
  - cargo install xargo || true

script:
  - xargo build --target $TARGET
  - xargo build --target $TARGET --release

#after_success:
#  - bash ci/after_success.sh