language: rust
rust: nightly
env: TARGET_BUILD=thumbv7m-none-eabi

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - binutils-arm-none-eabi
      - coreutils

before_install: set -e

install:
  - rustup target add $TARGET_BUILD

script:
  - cargo fmt --all -- --check
  - cargo check --target $TARGET_BUILD

#  - make build

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
