language: rust

matrix:
  include:
    - env: TARGET_BUILD=thumbv6m-none-eabi
    - env: TARGET_BUILD=thumbv7em-none-eabi
    - env: TARGET_BUILD=thumbv7em-none-eabihf
    - env: TARGET_BUILD=thumbv7m-none-eabi

before_install: 
  - set -e
  - rustup self update
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-none-eabi

install:
  - rustup override set nightly
  - rustup component add rust-src
  - rustup target add arm-unknown-linux-gnueabi
  - rustup target add armv7-unknown-linux-gnueabihf
  - source ~/.cargo/env || true
  - mv .cargo ._cargo
  - cargo install xargo || true
  - mv ._cargo .cargo

script:
  - xargo build --target $TARGET_BUILD
  - xargo build --target $TARGET_BUILD --release

#after_success:
#  - bash ci/after_success.sh

notifications:
  email:
    on_success: never