trigger:
- master

jobs:
- job: rustfmt
  displayName: 'Check Code Formatting'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: curl https://sh.rustup.rs -sSf | sh -s -- -y
    displayName: 'Install Rust'
  - script: $HOME/.cargo/bin/rustup component add rustfmt
    displayName: 'Install rustfmt'
  - script: $HOME/.cargo/bin/cargo fmt --all -- --check
    displayName: 'Check code formatting'

- job: check
  displayName: 'Build project'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      thumbv6:
        TARGET: thumbv7em-none-eabi
  steps:
  - script: curl https://sh.rustup.rs -sSf | sh -s -- -y
    displayName: 'Install Rust'
  - script: $HOME/.cargo/bin/rustup target add $TARGET
    displayName: 'Install target libraries'
  - script: $HOME/.cargo/bin/cargo check --target $TARGET
    displayName: 'Running `cargo check`'
