[package]
name = "mremote"
version = "0.0.2"
authors = ["Ferdia McKeogh"]
description = "Encrypted electric longboard remote with telemetry"
keywords = ["arm", "cortex-m"]
categories = ["embedded", "no-std"]
license = "AGPL-3.0-only"
repository = "https://github.com/chocol4te/mremote"


[profile.release]
opt-level = 1 # Only 0 and 1 work: need to fix
debug = true # Disabling *increases* size
rpath = false
lto = true
debug-assertions = true
codegen-units = 16 # Not ideal but didn't break build
panic = 'abort'
incremental = false
overflow-checks = true

[profile.dev]
incremental = false
codegen-units = 16

[dependencies]
cortex-m = "0.4.3"
cortex-m-rtfm = "0.3.2"
cortex-m-rtfm-macros = "0.3.1"
panic-abort = "0.2.0"
alloc-cortex-m = "0.3.4"


#TODO: Replace these with crates.io dependencies when available
[dependencies.cortex-m-rt]
git = "https://github.com/japaric/cortex-m-rt"
rev = "1865c7a"

[dependencies.embedded-graphics]
#git = "https://github.com/jamwaffles/embedded-graphics.git"
#rev = "93b16fd"
#tag = "0.1.1"
version = "0.1.1"

[dependencies.ssd1306]
git = "https://github.com/jamwaffles/ssd1306.git"
rev = "a6e1661"

[dependencies.stm32f103xx-hal]
git = "https://github.com/japaric/stm32f103xx-hal.git"
features = ["rt"]
rev = "330c904"
