[package]
name = "mremote"
version = "0.0.2"
authors = ["Ferdia McKeogh"]
description = "Encrypted electric longboard remote with telemetry"
keywords = ["arm", "cortex-m"]
categories = ["embedded", "no-std"]
license = "AGPL-3.0-only"
repository = "https://github.com/chocol4te/mremote"

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
opt-level = 3
codegen-units = 1
debug = true
lto = true

[dependencies]
cortex-m = "0.5.2"
cortex-m-rt = "0.5.1"
panic-semihosting = "0.3.0"
nb = "0.1.1"
cortex-m-semihosting = "0.3.0"
#cortex-m = "0.4.3"
#panic-abort = "0.1.1"
#alloc-cortex-m = "0.3.4"


#TODO: Replace these with crates.io dependencies when available
#[dependencies.cortex-m-rt]
#git = "https://github.com/japaric/cortex-m-rt"
#rev = "1865c7a"

#[dependencies.embedded-graphics]
#git = "https://github.com/jamwaffles/embedded-graphics.git"
#rev = "93b16fd"
#tag = "0.1.1"
#version = "0.1.1"

#[dependencies.ssd1306]
#git = "https://github.com/jamwaffles/ssd1306.git"
#rev = "a6e1661"

[dependencies.stm32f103xx-hal]
git = "https://github.com/chocol4te/stm32f103xx-hal.git"
features = ["rt"]
rev = "ee5cc9e"
