[package]
name = "mremote"
version = "0.0.2"
authors = ["Ferdia McKeogh"]
description = "Encrypted electric longboard remote with telemetry"
keywords = ["arm", "cortex-m"]
categories = ["embedded", "no-std"]
license = "Apache-2.0"
repository = "https://github.com/chocol4te/mremote"


[profile.release]
#opt-level = "s"
lto = true
debug = true

[profile.dev]
incremental = false
codegen-units = 1

[dependencies]
embedded-hal = "0.1.2"
cortex-m = "0.4.3"
aligned = "0.1.1"
cortex-m-rtfm = "0.3.2"
cortex-m-rtfm-macros = "0.3.1"
cortex-m-rt = "0.4.0"
panic-abort = "0.1.0"
alloc-cortex-m = "0.3.4"

[dependencies.embedded-graphics]
version = "0.1.1"

[dependencies.ssd1306]
git = "https://github.com/jamwaffles/ssd1306.git"
rev = "a6e1661"

# Must be installed from Git currently, not sure why it's not on crates.io
# TODO: Replace this with a "normal" dependency in the future
[dependencies.stm32f103xx-hal]
git = "https://github.com/japaric/stm32f103xx-hal.git"
#branch = "i2c-support"
features = ["rt"]
version = "*"
